/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
  interface Window {
    __TAURI_INVOKE__<T>(
      cmd: string,
      args?: Record<string, unknown>
    ): Promise<T>;
  }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

/**
 * 定义一个包装器函数来处理异步调用
 */
export function wrapGetSessionList(start: number, end: number) {
  return invoke()<CommandResult<Session[], string>>("wrap_get_session_list", {
    start,
    end,
  });
}

export type CommandResult<T, E> = { Ok: T } | { Err: E };
export type Session = { id: string; title: string; role_id: number; type: string }

export type SessionData = {
  id: number;
  sessionId: number;
  role: string;
  message: string;
  Session: Session | null;
};
