/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

/**
 * 定义一个包装器函数来处理异步调用
 */
export function wrapGetSessionList(start: number, end: number) {
    return invoke()<Session[]>("wrap_get_session_list", { start,end })
}

export function wrapGetSessionDataById(id: string) {
    return invoke()<SessionData[]>("wrap_get_session_data_by_id", { id })
}

export type Session = { id: string; title: string; role_id: number; type: string; createdAt: string; updatedAt: string }
export type SessionData = { id: number; sessionId: string; role: string; message: string; is_ask: boolean; is_memory: boolean; message_type: string; model: string; createdAt: string; updatedAt: string }
